export const STREETS=[-18,-6,6,18];
export const BUILDINGS={
 casa_chorizo:{name:'Casa chorizo',subtitle:'Habitaciones, galería y patio',wood:70,food:0,time:11,width:3,depth:6,size:6,capacity:4,description:'Aloja a 4 vecinos. Habitaciones en hilera sobre una medianera, galería y patio lateral; zaguán al frente y servicios al fondo.',icon:'house',footprint:'Lote angosto · 3 × 6'},
 almacen:{name:'Almacén',subtitle:'Provisiones a la vuelta',wood:90,food:25,time:13,width:3.6,depth:3.6,size:3.6,capacity:0,description:'Local a la calle, vidriera y depósito atrás. Produce 1 de yerba cada 5 segundos; la yerba permite invitar nuevos vecinos.',icon:'store',footprint:'Local y depósito · 3,6 × 3,6'},
 conventillo:{name:'Conventillo',subtitle:'Un patio, muchas historias',wood:150,food:35,time:20,width:6,depth:6,size:6,capacity:8,description:'Aloja a 8 vecinos. Cuartos alrededor de un patio compartido, galerías de acceso y servicios comunes al fondo.',icon:'users-round',footprint:'Patio compartido · 6 × 6'},
 huerta:{name:'Lote de soja',subtitle:'La cosecha del borde urbano',wood:40,food:0,time:7,width:3.4,depth:3.4,size:3.4,capacity:0,description:'Surcos de soja en un lote abierto. Produce 3 de soja cada 5 segundos para abastecer la economía del barrio.',icon:'sprout',footprint:'Cultivo de soja · 3,4 × 3,4'},
 taller:{name:'Taller',subtitle:'Oficios que levantan el barrio',wood:100,food:20,time:15,width:4,depth:4.8,size:4.8,capacity:0,description:'Nave de trabajo con portón, banco y depósito. Las herramientas aumentan un 25% la recuperación de materiales. El efecto no se acumula.',icon:'hammer',footprint:'Nave de trabajo · 4 × 4,8'},
 club:{name:'Club de barrio',subtitle:'La casa de todos',wood:140,food:30,time:18,width:6,depth:6,size:6,capacity:0,description:'Salón social, buffet y vereda de encuentro. Con un club terminado, invitar a un vecino cuesta 25 de soja y 3 de yerba. El beneficio no se acumula.',icon:'landmark',footprint:'Salón y buffet · 6 × 6'},
 potrero:{name:'Potrero de fútbol',subtitle:'La pelota siempre vuelve',wood:45,food:0,time:8,width:7,depth:7,size:7,capacity:0,description:'Un lote abierto, césped desparejo y dos arcos. Un espacio de juego para la cuadra; no produce recursos ni suma viviendas.',icon:'goal',footprint:'Espacio abierto · 7 × 7'},
};
export function canAfford(resources,spec){return resources.wood>=spec.wood&&resources.food>=spec.food;}
export function footprint(spec,rotation=0){const swap=Math.round(rotation/(Math.PI/2))%2!==0;return {width:swap?spec.depth:spec.width,depth:swap?spec.width:spec.depth};}
export function overlaps(x,z,width,depth,buildings){return buildings.some(b=>Math.abs(b.x-x)<(b.width+width)/2+.35&&Math.abs(b.z-z)<(b.depth+depth)/2+.35);}
export function validTerrain(x,z,width=0,depth=width){return Math.abs(x)+width/2<25.4&&Math.abs(z)+depth/2<28&&STREETS.every(p=>Math.abs(x-p)>width/2+1.65&&Math.abs(z-p)>depth/2+1.65);}
export function facesStreet(x,z,spec,rotation){const dx=Math.round(Math.sin(rotation)),dz=Math.round(Math.cos(rotation));const frontX=x+dx*spec.depth/2,frontZ=z+dz*spec.depth/2;return STREETS.some(p=>{const distance=dx?(p-frontX)*dx:(p-frontZ)*dz;return distance>1.6&&distance<3.2;});}
