import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createIcons, Sun, Trees, Wheat, Leaf, UsersRound, VolumeX, Volume2, CircleHelp, Pause, Circle, Flag, Rotate3d, Plus, Minus, Focus, Navigation, Hammer, Sunrise, Map as MapIcon, Expand, MousePointer2, House, Store, Warehouse, Sprout, Wind, X, ArrowRight, Move, Play, Save, FolderOpen, UserRound, Square, Beef, UserPlus, Landmark, Goal } from 'lucide';
import { BUILDINGS, STREETS, BLOCKS, MAP_HALF, BLOCK_HALF, canAfford, overlaps, footprint, lotPlacement, allPlacements } from './economy.js';
import { createWorld, architecture, buildingPreviews } from './world.js';
import manualUrl from '../REGLAS_Y_MANUAL.md?url';
import './style.css';

const $ = (id) => document.getElementById(id);
const icons={Sun,Trees,Wheat,Leaf,UsersRound,VolumeX,Volume2,CircleHelp,Pause,Circle,Flag,Rotate3d,Plus,Minus,Focus,Navigation,Hammer,Sunrise,Map:MapIcon,Expand,MousePointer2,House,Store,Warehouse,Sprout,Wind,X,ArrowRight,Move,Play,Save,FolderOpen,UserRound,Square,Beef,UserPlus,Landmark,Goal};
const icon = (name, cls='') => `<i data-lucide="${name}" class="${cls}"></i>`;
const app = $('app');
app.innerHTML = `
 <main id="game" aria-label="Mapa interactivo del conurbano bonaerense">
  <div id="world"></div><div class="vignette"></div>
  <header class="topbar">
   <a class="brand" href="#" aria-label="Age of Conurban">${icon('sun')}<span>AGE OF <b>CONURBAN</b></span><span class="alpha">ALPHA</span></a>
   <div class="resources">
    <div class="resource" title="Materiales · recuperalos de los acopios de ladrillos y madera">${icon('warehouse')}<div><span>MATERIALES</span><strong id="wood">280</strong></div><small id="wood-rate">+0</small></div>
    <div class="resource" title="Soja · cosechala en los lotes del borde del barrio">${icon('sprout')}<div><span>SOJA</span><strong id="food">120</strong></div><small id="food-rate">+0</small></div>
    <div class="resource yerba" title="Yerba · provisiones del almacén y los puestos">${icon('leaf')}<div><span>YERBA</span><strong id="yerba">20</strong></div><small id="yerba-rate">+0</small></div>
    <div class="resource population" title="Vecinos / capacidad de alojamiento">${icon('users-round')}<div><span>POBLACIÓN</span><strong><span id="pop">5</span><em>/</em><span id="capacity">8</span></strong></div></div>
   </div>
   <div class="top-actions"><button id="sound" class="icon-button" title="Activar ambiente" aria-label="Activar sonido">${icon('volume-x')}</button><button id="help" class="icon-button" title="Cómo jugar" aria-label="Cómo jugar">${icon('circle-help')}</button><button id="pause" class="icon-button" title="Pausar" aria-label="Pausar">${icon('pause')}</button></div>
  </header>
  <section class="region-card"><div class="eyebrow"><span class="live-dot"></span> PARTIDA LIBRE <span>·</span> UN JUGADOR</div><h1>Tero Cosechado<span>01</span></h1><p>Un rincón del conurbano.</p><div class="region-meta">${icon('sun')}<span>Una tarde de primavera</span><span class="region-line"></span><b id="clock">00:00</b></div></section>
  <aside class="objectives"><div class="section-label">UN BARRIO EN MARCHA <span id="goal-count">0/3</span></div><h2>Echar raíces</h2><p>Una cuadra, un patio.<br>Y un barrio por construir.</p><div id="goal-wood" class="goal">${icon('circle')}<span>Recuperá 30 materiales</span><b id="gathered">0/30</b></div><div id="goal-home" class="goal">${icon('circle')}<span>Construí una casa chorizo</span></div><div id="goal-neighbor" class="goal">${icon('circle')}<span>Invitá a un nuevo vecino</span></div><div class="objective-foot">${icon('flag')}<span>Tu cuadra. A tu ritmo.</span></div></aside>
  <div id="toast" role="status" aria-live="polite"></div>
  <div id="placement-hint" class="placement-hint hidden"></div>
  <div class="map-tools"><button id="rotate" class="icon-button" title="Rotar cámara" aria-label="Rotar cámara">${icon('rotate-3d')}</button><button id="zoom-in" class="icon-button" title="Acercar" aria-label="Acercar">${icon('plus')}</button><button id="zoom-out" class="icon-button" title="Alejar" aria-label="Alejar">${icon('minus')}</button><button id="home-view" class="icon-button" title="Centrar pueblo" aria-label="Centrar pueblo">${icon('focus')}</button></div>
  <div class="compass"><span>N</span>${icon('navigation')}<small>S</small></div>
  <footer class="bottom-area">
   <section class="selection-panel" id="selection"></section>
   <section class="build-panel"><div class="build-heading"><div class="build-tabs"><button class="active" id="build-tab">${icon('hammer')} Construir</button><button id="neighbors-tab">${icon('users-round')} Vecinos <span id="neighbor-count">5</span></button></div><span class="era">${icon('sunrise')} LOS COMIENZOS</span></div><div id="build-content"></div></section>
   <section class="minimap-panel"><div class="mini-heading"><span>${icon('map')} TERO COSECHADO</span><b>3 × 3 manzanas</b></div><canvas id="minimap" width="220" height="138" aria-label="Minimapa: hacé clic para mover la cámara"></canvas><div class="mini-footer"><span class="live-dot"></span> Conurbano bonaerense ${icon('expand')}</div></section>
  </footer>
  <div class="bottom-hints"><span>${icon('mouse-pointer-2')} Seleccionar <kbd>clic</kbd></span><span>Dar una orden <kbd>clic derecho</kbd></span><span>Mover cámara <kbd>arrastrar</kbd> <kbd>W A S D</kbd></span><span>Cancelar <kbd>Esc</kbd></span><span class="version">HECHO EN ESTAS TIERRAS <span>✦</span> v0.1</span></div>
  <dialog id="help-dialog"><button class="close-dialog icon-button" aria-label="Cerrar">${icon('x')}</button><div class="dialog-sun">${icon('sun')}</div><div class="eyebrow">BIENVENIDO A TU RINCÓN</div><h2>Un barrio empieza con vos.</h2><p>Construí Tero Cosechado, un barrio imaginario del conurbano bonaerense.</p><div class="help-grid"><div>${icon('mouse-pointer-2')}<b>Elegí un vecino</b><p>Hacé clic sobre un habitante o elegilo en la pestaña Vecinos.</p></div><div>${icon('warehouse')}<b>Ponelo a trabajar</b><p>Con un vecino seleccionado, hacé clic derecho en un acopio de materiales, un cultivo de soja o un puesto de yerba. En una pantalla táctil, tocá el recurso.</p></div><div>${icon('hammer')}<b>Levantá tu barrio</b><p>Elegí un edificio y hacé clic en un terreno libre. Necesitás un vecino disponible para construirlo.</p></div><div>${icon('move')}<b>Recorré el barrio</b><p>Arrastrá el mapa, o usá WASD o flechas, para moverte. Rueda para acercarte. Arrastrá con el botón central para girar.</p></div></div><p class="help-note">Cada manzana tiene 18 lotes: las obras se ubican solas con el frente a la calle. Los cultivos de soja se ubican en el borde urbano. Esta etapa es para un jugador, sin combate.</p><button id="start-playing" class="primary-button">Vamos al barrio ${icon('arrow-right')}</button></dialog>
  <dialog id="pause-dialog"><div class="dialog-sun">${icon('pause')}</div><div class="eyebrow">UN MATE Y SEGUIMOS</div><h2>El barrio te espera.</h2><p>La partida está en pausa.</p><button id="resume" class="primary-button">Seguir jugando ${icon('play')}</button><button id="save" class="secondary-button">${icon('save')} Guardar en este dispositivo</button><button id="load" class="secondary-button">${icon('folder-open')} Cargar partida guardada</button><a class="secondary-button" href="${manualUrl}" download="REGLAS_Y_MANUAL.md">${icon('circle-help')} Descargar manual completo</a><p class="save-note" id="save-note"></p></dialog>
 </main>`;
function refreshIcons(){createIcons({icons,attrs:{'stroke-width':1.65}});}

const state={resources:{wood:280,food:120,yerba:20},buildings:[],units:[],nodes:[], selected:null,placing:null,paused:false,time:0,gathered:0,builtHome:false,invited:false,tab:'build',speed:1};
let seed=42;
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const scene=new THREE.Scene();scene.background=new THREE.Color('#a8b8a0');scene.fog=new THREE.Fog('#a8b8a0',110,240);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.localClippingEnabled=true;
renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;
$('world').appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Mapa 3D interactivo');
const HOME=new THREE.Vector3(-1,0,9),CAMERA_OFFSET=new THREE.Vector3(51,58.5,64.5);
const camera=new THREE.OrthographicCamera(-30,30,20,-20,.1,400);camera.position.copy(HOME).add(CAMERA_OFFSET);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(HOME);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxPolarAngle=Math.PI/2.6;controls.minPolarAngle=.35;controls.minZoom=.45;controls.maxZoom=2.8;controls.enablePan=false;controls.mouseButtons={LEFT:null,MIDDLE:THREE.MOUSE.ROTATE,RIGHT:null};controls.touches={ONE:null,TWO:THREE.TOUCH.DOLLY_ROTATE};controls.update();
scene.add(new THREE.HemisphereLight('#f3eacb','#586d40',2.4));
const sun=new THREE.DirectionalLight('#fff0cb',3.1);sun.position.set(-38,63,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-68,right:68,top:68,bottom:-68,near:1,far:230});sun.shadow.normalBias=.07;sun.shadow.bias=-.0002;scene.add(sun);
const materials={};
function mat(color){return materials[color]??=new THREE.MeshStandardMaterial({color,roughness:1});}
function mesh(geo,color,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geo,typeof color==='string'?mat(color):color);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,c,x,y,z,p){return mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,p);}
function cone(r,h,n,c,x,y,z,p){return mesh(new THREE.ConeGeometry(r,h,n),c,x,y,z,p);}
function cylinder(rt,rb,h,c,x,y,z,p,n=8){return mesh(new THREE.CylinderGeometry(rt,rb,h,n),c,x,y,z,p);}
function ellipsoid(rx,ry,rz,c,x,y,z,p){const m=mesh(new THREE.IcosahedronGeometry(1,1),c,x,y,z,p);m.scale.set(rx,ry,rz);return m;}
const {pickables,obstacles,register,makeBuilding,removeBuilding,setProgress,animateWorld}=createWorld(scene,state);
const previews=buildingPreviews();
const unitNames=['Ramón','Juana','Pedro','Rosa','Segundo','Elena','Inés','Mateo','Amalia','Pascual','Lola','Jacinto'];
function addUnit(x,z,name){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);const index=state.units.length,color=['#628b9a','#a75740','#c1a266','#5c7866','#896b80'][index%5];
const torso=cone(.26,.58,5,color,0,.73,0,g);torso.rotation.y=Math.PI/4;box(.35,.22,.24,'#514e3c',0,.43,0,g);const legs=[];for(const dx of [-.12,.12])legs.push(box(.13,.36,.15,'#504b3b',dx,.2,0,g));ellipsoid(.17,.2,.16,'#c99867',0,1.13,0,g);cylinder(.21,.21,.045,'#c8ad70',0,1.32,0,g);cylinder(.17,.19,.12,'#b29558',0,1.39,0,g);box(.22,.025,.15,'#b29558',0,1.33,.18,g);for(const dx of [-.26,.26]){const arm=box(.12,.4,.13,color,dx,.77,0,g);arm.rotation.z=dx>0?-.15:.15;}
const u={kind:'unit',name:name||unitNames[index%unitNames.length],x,z,group:g,legs,job:null,target:null,path:[],carried:0,work:0,walk:0};state.units.push(u);register(g,u);return u;}
addUnit(-4.5,13.4);addUnit(-3,13.9);addUnit(-1.5,13.4);addUnit(0,13.9);addUnit(1.5,13.4);
const selectionRing=mesh(new THREE.RingGeometry(.55,.64,48),new THREE.MeshBasicMaterial({color:'#eed396',side:THREE.DoubleSide}),0,.3,0);selectionRing.rotation.x=-Math.PI/2;selectionRing.visible=false;
// Buildings and resources are outlined with a rectangle that matches their footprint.
const selectionFrame=new THREE.Group();for(let i=0;i<4;i++)selectionFrame.add(new THREE.Mesh(new THREE.BoxGeometry(1,.04,1),selectionRing.material));selectionFrame.visible=false;scene.add(selectionFrame);
function frameAround(e){const w=e.width+.5,d=e.depth+.5,t=.2,[north,south,west,east]=selectionFrame.children;north.scale.set(w+t,1,t);north.position.set(0,0,-d/2);south.scale.set(w+t,1,t);south.position.set(0,0,d/2);west.scale.set(t,1,d);west.position.set(-w/2,0,0);east.scale.set(t,1,d);east.position.set(w/2,0,0);selectionFrame.position.set(e.x,.34,e.z);}
const destinationRing=mesh(new THREE.RingGeometry(.25,.32,24),new THREE.MeshBasicMaterial({color:'#efe2a6',transparent:true,opacity:.8,side:THREE.DoubleSide}),0,.075,0);destinationRing.rotation.x=-Math.PI/2;destinationRing.visible=false;
let destinationTTL=0,ghost=null,ghostValid=false,placement=null,pointerWorld=null,toastTimer,ambient=null,audioContext=null;
function capacity(){return state.buildings.filter(b=>b.progress>=1).reduce((n,b)=>n+(BUILDINGS[b.type]?.capacity||0),0);}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3700);}
function select(entity){state.selected=entity;const framed=!!entity&&entity.kind!=='unit';selectionRing.visible=!!entity&&!framed;selectionFrame.visible=framed;if(framed)frameAround(entity);else if(entity)selectionRing.position.set(entity.x,.3,entity.z);renderSelection();}
function unitStatus(u){return u.job==='build'?'Construyendo':u.job==='wood'?'Recuperando materiales':u.job==='food'?'Cosechando soja':u.job==='yerba'?'Retirando yerba':u.path.length?'Caminando':'Disponible';}
function renderSelection(){const e=state.selected;let html='';if(!e){html=`<div class="selection-title"><span class="section-label">TU BARRIO</span><span class="status-dot"></span></div><div class="portrait village">${icon('house')}</div><div class="selection-copy"><h3>Hacelo crecer.</h3><p>Elegí un vecino para<br>empezar a trabajar.</p></div><div class="selection-tip">${icon('mouse-pointer-2')} Hacé clic en el mapa</div>`;}
else if(e.kind==='unit'){html=`<div class="selection-title"><span class="section-label">VECINO DEL BARRIO</span><span class="status-dot"></span></div><div class="portrait person">${icon('user-round')}</div><div class="selection-copy"><h3>${e.name}</h3><p id="unit-status">${unitStatus(e)}</p><span class="unit-health"><i></i></span></div><div class="selection-tip">${icon('mouse-pointer-2')} Clic derecho para mover o recolectar</div><button id="stop-unit" class="small-button">${icon('square')} Detener</button>`;}
else if(e.kind==='resource'){html=`<div class="selection-title"><span class="section-label">RECURSO NATURAL</span></div><div class="portrait">${icon(e.type==='wood'?'warehouse':e.type==='food'?'sprout':'leaf')}</div><div class="selection-copy"><h3>${e.name}</h3><p><b id="resource-left">${Math.ceil(e.remaining)}</b> disponibles</p></div><div class="selection-tip">Asigná un vecino para recolectar.</div><button id="assign-worker" class="small-button">${icon('user-plus')} Asignar vecino</button>`;}
else{html=`<div class="selection-title"><span class="section-label">${e.progress<1?'EN CONSTRUCCIÓN':'EDIFICIO DEL BARRIO'}</span></div><div class="portrait">${icon(BUILDINGS[e.type]?.icon||'landmark')}</div><div class="selection-copy"><h3>${e.name}</h3><p id="building-status">${e.progress<1?Math.floor(e.progress*100)+'% construido':e.type==='centro'?'El punto de partida':BUILDINGS[e.type].subtitle}</p></div><div class="selection-tip building-description">${e.type==='centro'?'Invitá vecinos y organizá el crecimiento del barrio.':BUILDINGS[e.type].description}</div>${e.type==='centro'?`<button id="invite" class="small-button">${icon('user-plus')} Invitar vecino <span>${invitationCost().food} ${icon('sprout')} · ${invitationCost().yerba} ${icon('leaf')}</span></button>`:e.progress<1?'<button id="resume-build" class="small-button">Asignar constructor</button>':''}`;}
$('selection').innerHTML=html;refreshIcons();if($('stop-unit'))$('stop-unit').onclick=()=>{e.job=null;e.target=null;e.path=[];renderSelection();};if($('invite'))$('invite').onclick=invite;if($('assign-worker'))$('assign-worker').onclick=()=>{const u=state.units.find(u=>!u.job&&!u.path.length)||state.units[0];orderResource(u,e);select(u);};if($('resume-build'))$('resume-build').onclick=()=>{const u=state.units.find(u=>!u.job&&!u.path.length);if(!u)return toast('Necesitás un vecino disponible.');assignBuild(u,e);};}
function renderBuild(){if(state.tab==='neighbors'){$('build-content').innerHTML=`<div class="neighbors-list">${state.units.map((u,i)=>`<button class="neighbor-card" data-unit="${i}"><span class="neighbor-face">${icon('user-round')}</span><b>${u.name}</b><small>${unitStatus(u)}</small></button>`).join('')}<button class="neighbor-card invite-card" id="invite-list">${icon('user-plus')}<b>Invitar</b><small>${invitationCost().food} soja · ${invitationCost().yerba} yerba</small></button></div>`;document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>select(state.units[+b.dataset.unit]));$('invite-list').onclick=invite;}
else{$('build-content').innerHTML=`<div class="building-cards">${Object.entries(BUILDINGS).map(([key,spec],i)=>`<button class="building-card ${state.placing===key?'chosen':''}" data-building="${key}" title="${spec.footprint}. ${spec.description}"><span class="building-shortcut">${i+1}</span><div class="building-illustration"><img src="${previews[key]}" alt="${spec.subtitle}"/></div><strong>${spec.name}</strong><span class="cost">${icon('warehouse')} ${spec.wood}${spec.food?`<span>${icon('sprout')} ${spec.food}</span>`:''}</span></button>`).join('')}</div>`;document.querySelectorAll('[data-building]').forEach(b=>b.onclick=()=>beginPlacement(b.dataset.building));}refreshIcons();}
function invitationCost(){return state.buildings.some(b=>b.type==='club'&&b.progress>=1)?{food:25,yerba:3}:{food:35,yerba:5};}
function invite(){const cost=invitationCost();if(state.units.length>=capacity())return toast('No hay lugar. Construí una casa chorizo o un conventillo.');if(state.resources.food<cost.food||state.resources.yerba<cost.yerba)return toast(`Necesitás ${cost.food} de soja y ${cost.yerba} de yerba para invitar a un vecino.`);state.resources.food-=cost.food;state.resources.yerba-=cost.yerba;const u=addUnit(-4+rand()*4,13.2+rand()*.9);state.invited=true;select(u);renderBuild();updateHUD();toast(`${u.name} llegó al barrio. ¡Una mano más!`);}
function beginPlacement(type){
 if(state.paused)return;if(!canAfford(state.resources,BUILDINGS[type]))return toast('Faltan materiales o soja para este edificio.');if(!state.units.some(u=>!u.job&&!u.path.length))return toast('Necesitás un vecino disponible. Detené a uno para construir.');
 cancelPlacement();state.placing=type;ghost=architecture(type);ghost.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.48;o.material.depthWrite=false;o.castShadow=false;}});scene.add(ghost);ghost.visible=false;
 $('placement-hint').innerHTML=icon('hammer')+' Ubicá: '+BUILDINGS[type].name+' <span>Elegí un lote: el frente mira a la calle</span><button id="cancel-build">Cancelar <kbd>Esc</kbd></button>';
 $('placement-hint').classList.remove('hidden');$('cancel-build').onclick=cancelPlacement;renderBuild();updateGhost();
}
function cancelPlacement(){state.placing=null;if(ghost){scene.remove(ghost);ghost.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});ghost=null;}$('placement-hint').classList.add('hidden');renderBuild();}

function updateGhost(){if(!ghost||!pointerWorld)return;placement=lotPlacement(BUILDINGS[state.placing],pointerWorld.x,pointerWorld.z);ghost.visible=!!placement;ghostValid=canPlace(placement,state.placing);if(!placement)return;ghost.position.set(placement.x,.2,placement.z);ghost.rotation.y=placement.rotation;ghost.traverse(o=>{if(o.isMesh)o.material.color.set(ghostValid?'#afd39d':'#e27263');});}
const inside=(x,z,r,pad)=>Math.abs(x-r.x)<r.width/2+pad&&Math.abs(z-r.z)<r.depth/2+pad;
// Lots only need to be free: neighbouring buildings may share a party wall, and resources must be used up first.
function canPlace(spot,type){if(!spot)return false;const r={x:spot.x,z:spot.z,...footprint(BUILDINGS[type],spot.rotation)};return !overlaps(r.x,r.z,r.width,r.depth,state.buildings,-.05)&&!state.nodes.some(n=>n.remaining>0&&overlaps(n.x,n.z,n.width,n.depth,[r],.05));}
// Neighbours standing on a new lot step out to the nearest sidewalk-side edge and resume what they were doing.
function evictUnits(b){for(const u of state.units){if(!inside(u.x,u.z,b,.3))continue;const exits=[{x:b.x-b.width/2-.6,z:u.z},{x:b.x+b.width/2+.6,z:u.z},{x:u.x,z:b.z-b.depth/2-.6},{x:u.x,z:b.z+b.depth/2+.6}].filter(p=>isWalkable(p.x,p.z)).sort((a,c)=>Math.hypot(a.x-u.x,a.z-u.z)-Math.hypot(c.x-u.x,c.z-u.z));if(!exits.length)continue;Object.assign(u,exits[0]);u.group.position.set(u.x,0,u.z);if(u.target&&u.job){const route=routeToWork(u,u.target);u.path=route||[];if(!route){u.job=null;u.target=null;}}else u.path=[];}}
function assignBuild(u,b){u.job='build';u.target=b;u.work=0;const route=routeToWork(u,b);if(route)u.path=route;else{u.path=[];u.job=null;u.target=null;toast('No hay un camino libre hasta la obra.');}renderSelection();}
function placeBuilding(){if(!placement||!ghostValid)return toast('Buscá un lote libre: no puede tener otra construcción ni un recurso sin agotar.');const type=state.placing,spec=BUILDINGS[type],spot=placement,u=state.units.find(u=>!u.job&&!u.path.length);if(!u)return toast('Necesitás un vecino disponible.');if(!canAfford(state.resources,spec))return toast('No alcanzan los recursos.');state.resources.wood-=spec.wood;state.resources.food-=spec.food;const b=makeBuilding(type,spot.x,spot.z,false,spot.rotation);b.userBuilt=true;b.corner=spot.corner;evictUnits(b);assignBuild(u,b);if(u.job!=='build'){state.resources.wood+=spec.wood;state.resources.food+=spec.food;removeBuilding(b);state.buildings.splice(state.buildings.indexOf(b),1);cancelPlacement();updateHUD();return;}cancelPlacement();select(b);updateHUD();toast(`${u.name} está construyendo: ${spec.name}${spot.corner&&type==='almacen'?' en la esquina':''}.`);}
// A* uses rectangular rotated footprints and keeps the railway out of pedestrian routes.
function isWalkable(x,z,ignore=null){if(Math.abs(x)>MAP_HALF||Math.abs(z)>MAP_HALF)return false;return !state.buildings.some(b=>b!==ignore&&inside(x,z,b,.24))&&!obstacles.some(o=>inside(x,z,o,.24))&&!state.nodes.some(n=>n!==ignore&&n.remaining>0&&Math.abs(x-n.x)<n.width/2+.2&&Math.abs(z-n.z)<n.depth/2+.2);}
// Workers stand on a free spot around the target's edge instead of its centre, one per spot.
function workSpot(u,t){const hw=t.width/2+.55,hd=t.depth/2+.55,spots=[];for(const [ax,az,len] of [[1,0,hd],[-1,0,hd],[0,1,hw],[0,-1,hw]])for(let s=-len+.3;s<=len-.3+1e-6;s+=.8)spots.push(ax?{x:t.x+ax*hw,z:t.z+s}:{x:t.x+s,z:t.z+az*hd});
 const taken=state.units.filter(o=>o!==u&&((o.target===t&&o.spot)||!o.path.length)).map(o=>o.target===t&&o.spot?o.spot:{x:o.x,z:o.z});
 return spots.filter(p=>isWalkable(p.x,p.z)&&!taken.some(o=>Math.hypot(o.x-p.x,o.z-p.z)<.75)).sort((a,b)=>Math.hypot(a.x-u.x,a.z-u.z)-Math.hypot(b.x-u.x,b.z-u.z));}
function routeToWork(u,t){for(const spot of workSpot(u,t).slice(0,6)){const path=findPath(u.x,u.z,spot.x,spot.z),last=path.at(-1)??{x:u.x,z:u.z};if(Math.hypot(last.x-spot.x,last.z-spot.z)<1.6){path.push(spot);u.spot=spot;return path;}}u.spot=null;return null;}
function findPath(sx,sz,tx,tz){const ignore=state.nodes.find(n=>n.remaining>0&&Math.abs(sx-n.x)<n.width/2+.2&&Math.abs(sz-n.z)<n.depth/2+.2)||null,cells=new Map(),walkable=(x,z)=>{const k=x*1000+z;let v=cells.get(k);if(v===undefined){v=isWalkable(x,z,ignore);cells.set(k,v);}return v;};let gx=Math.round(tx),gz=Math.round(tz);if(!walkable(gx,gz)){let best=null;for(let r=1;r<6&&!best;r++)for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++){if(walkable(gx+dx,gz+dz)){const d=Math.hypot(gx+dx-sx,gz+dz-sz);if(!best||d<best.d)best={x:gx+dx,z:gz+dz,d};}}if(!best)return[];gx=best.x;gz=best.z;}
 const start={x:Math.round(sx),z:Math.round(sz),g:0},key=(x,z)=>x*1000+z,seen=new Map([[key(start.x,start.z),start]]),closed=new Set();start.f=Math.hypot(gx-start.x,gz-start.z);
 const heap=[start],push=n=>{heap.push(n);let i=heap.length-1;while(i){const p=(i-1)>>1;if(heap[p].f<=n.f)break;heap[i]=heap[p];i=p;}heap[i]=n;},pop=()=>{const top=heap[0],last=heap.pop();if(heap.length){let i=0;for(;;){let c=2*i+1;if(c>=heap.length)break;if(c+1<heap.length&&heap[c+1].f<heap[c].f)c++;if(heap[c].f>=last.f)break;heap[i]=heap[c];i=c;}heap[i]=last;}return top;};
 for(let step=0;heap.length&&step<40000;step++){const cur=pop(),ck=key(cur.x,cur.z);if(closed.has(ck))continue;closed.add(ck);if(cur.x===gx&&cur.z===gz){const path=[];let n=cur;while(n.parent){path.unshift({x:n.x,z:n.z});n=n.parent;}return path;}
  for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const x=cur.x+dx,z=cur.z+dz,k=key(x,z);if(closed.has(k)||!walkable(x,z)||(dx&&dz&&(!walkable(cur.x+dx,cur.z)||!walkable(cur.x,cur.z+dz))))continue;const cost=cur.g+(dx&&dz?1.414:1);const old=seen.get(k);if(old&&cost>=old.g)continue;const n={x,z,g:cost,f:cost+Math.hypot(gx-x,gz-z),parent:cur};seen.set(k,n);push(n);}}
 return[];
}
function orderResource(u,node){if(node.remaining<=0)return toast('Este recurso se agotó.');const route=routeToWork(u,node);if(!route)return toast('No hay lugar libre para trabajar en ese recurso.');u.path=route;u.job=node.type;u.target=node;u.work=0;toast(`${u.name}: ${node.type==='wood'?'a recuperar materiales':node.type==='food'?'a cosechar soja':'a retirar yerba'}.`);renderSelection();}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),groundPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
function rayAt(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);pointerWorld=raycaster.ray.intersectPlane(groundPlane,new THREE.Vector3());return raycaster.intersectObjects(pickables,false).find(hit=>hit.object.visible&&hit.object.parent?.visible&&hit.object.userData.entity?.remaining!==0)?.object.userData.entity;}
renderer.domElement.addEventListener('pointermove',e=>{const entity=rayAt(e);if(!drag.moved||drag.id===null)renderer.domElement.style.cursor=state.placing?'crosshair':entity?'pointer':'default';updateGhost();});
let pointerDown=null;renderer.domElement.addEventListener('pointerdown',e=>{pointerDown={x:e.clientX,y:e.clientY};});
// Dragging with the left button or one finger pans the barrio; a short press still selects or orders.
const touches=new Set(),drag={id:null,moved:false,grab:null};
function groundAt(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.ray.intersectPlane(groundPlane,new THREE.Vector3());}
function panBy(delta){const next=controls.target.clone().add(delta);next.x=Math.max(-MAP_HALF,Math.min(MAP_HALF,next.x));next.z=Math.max(-MAP_HALF,Math.min(MAP_HALF,next.z));const move=next.sub(controls.target);move.y=0;controls.target.add(move);camera.position.add(move);camera.updateMatrixWorld();}
renderer.domElement.addEventListener('pointerdown',e=>{touches.add(e.pointerId);if(e.button===0&&touches.size===1&&!state.paused){drag.id=e.pointerId;drag.x=e.clientX;drag.y=e.clientY;drag.moved=false;drag.grab=groundAt(e);}else drag.id=null;});
renderer.domElement.addEventListener('pointermove',e=>{if(drag.id!==e.pointerId||!drag.grab)return;if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8){drag.moved=true;renderer.domElement.style.cursor='grabbing';}if(!drag.moved)return;const now=groundAt(e);if(now)panBy(drag.grab.clone().sub(now));});
for(const type of ['pointerup','pointercancel'])renderer.domElement.addEventListener(type,e=>{touches.delete(e.pointerId);if(drag.id===e.pointerId){drag.id=null;if(drag.moved)renderer.domElement.style.cursor=state.placing?'crosshair':'default';}});
renderer.domElement.addEventListener('pointerup',e=>{if(state.paused||!pointerDown||Math.hypot(pointerDown.x-e.clientX,pointerDown.y-e.clientY)>8)return;if(e.button===2){issueOrder(e);return;}if(e.button!==0)return;const entity=rayAt(e);if(state.placing){updateGhost();placeBuilding();return;}if(e.pointerType==='touch'&&state.selected?.kind==='unit'&&entity?.kind==='resource'){orderResource(state.selected,entity);return;}if(e.pointerType==='touch'&&state.selected?.kind==='unit'&&!entity){moveSelected();return;}select(entity||null);});
function moveSelected(){const u=state.selected;if(u?.kind!=='unit'||!pointerWorld)return;const route=findPath(u.x,u.z,pointerWorld.x,pointerWorld.z);if(!route.length)return toast('No se puede llegar a ese lugar.');u.path=route;u.job=null;u.target=null;destinationRing.position.set(route.at(-1).x,.08,route.at(-1).z);destinationRing.visible=true;destinationTTL=1.2;renderSelection();}
function issueOrder(e){if(state.paused)return;if(state.placing){cancelPlacement();return;}const entity=rayAt(e);if(state.selected?.kind!=='unit')return toast('Primero elegí un vecino.');if(entity?.kind==='resource')orderResource(state.selected,entity);else if(entity?.kind==='building'&&entity.progress<1)assignBuild(state.selected,entity);else moveSelected();}
renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
const keys=new Set();addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.repeat)return;if(e.key==='Escape'){if(state.placing)cancelPlacement();else if($('help-dialog').open){$('help-dialog').close();state.paused=false;}else togglePause();}if(e.code==='Space'&&!$('help-dialog').open)togglePause();if(!state.paused&&/^[1-7]$/.test(e.key))beginPlacement(Object.keys(BUILDINGS)[+e.key-1]);});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());
function togglePause(force){state.paused=force??!state.paused;if(state.paused){if(!$('pause-dialog').open)$('pause-dialog').showModal();}else $('pause-dialog').close();}
$('pause').onclick=()=>togglePause();$('resume').onclick=()=>togglePause(false);$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();togglePause(false);});
$('help').onclick=()=>{state.paused=true;$('help-dialog').showModal();};function closeHelp(){$('help-dialog').close();state.paused=false;}$('start-playing').onclick=closeHelp;document.querySelector('.close-dialog').onclick=closeHelp;$('help-dialog').addEventListener('cancel',closeHelp);
$('zoom-in').onclick=()=>{camera.zoom=Math.min(2.8,camera.zoom*1.2);camera.updateProjectionMatrix();};$('zoom-out').onclick=()=>{camera.zoom=Math.max(.45,camera.zoom/1.2);camera.updateProjectionMatrix();};
function centerView(){lookAt(HOME.x,HOME.z);camera.zoom=1;camera.updateProjectionMatrix();}
$('home-view').onclick=centerView;$('rotate').onclick=()=>{const offset=camera.position.clone().sub(controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),Math.PI/4);camera.position.copy(controls.target).add(offset);};
$('build-tab').onclick=()=>{state.tab='build';$('build-tab').classList.add('active');$('neighbors-tab').classList.remove('active');renderBuild();};$('neighbors-tab').onclick=()=>{state.tab='neighbors';$('build-tab').classList.remove('active');$('neighbors-tab').classList.add('active');renderBuild();};
$('sound').onclick=()=>{if(ambient){audioContext.suspend();ambient=false;}else if(audioContext){audioContext.resume();ambient=true;}else{audioContext=new(window.AudioContext||window.webkitAudioContext)();const buffer=audioContext.createBuffer(1,audioContext.sampleRate*3,audioContext.sampleRate),data=buffer.getChannelData(0);let v=0;for(let i=0;i<data.length;i++){v=(v+(Math.random()*2-1)*.025)/1.025;data[i]=v;}const source=audioContext.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audioContext.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;const gain=audioContext.createGain();gain.gain.value=.23;source.connect(filter).connect(gain).connect(audioContext.destination);source.start();ambient=true;}$('sound').innerHTML=icon(ambient?'volume-2':'volume-x');$('sound').setAttribute('aria-label',ambient?'Desactivar sonido':'Activar sonido');refreshIcons();};
function serialize(){return {version:3,resources:state.resources,time:state.time,gathered:state.gathered,builtHome:state.builtHome,invited:state.invited,buildings:state.buildings.filter(b=>b.userBuilt).map(b=>({type:b.type,x:b.x,z:b.z,rotation:b.rotation,progress:b.progress,corner:!!b.corner})),units:state.units.map(u=>({name:u.name,x:u.x,z:u.z})),nodes:state.nodes.map(n=>n.remaining)};}
$('save').onclick=()=>{try{localStorage.setItem('conurban-barrio-v3',JSON.stringify(serialize()));$('save-note').textContent='Partida guardada en este dispositivo.';}catch{$('save-note').textContent='No se pudo guardar: el almacenamiento del navegador no está disponible.';}};
$('load').onclick=()=>{try{const raw=localStorage.getItem('conurban-barrio-v3');if(!raw){$('save-note').textContent='Todavía no hay una partida guardada.';return;}const s=JSON.parse(raw);if(s.version!==3||!s.resources||!Array.isArray(s.units)||!Array.isArray(s.buildings)||!Array.isArray(s.nodes))throw Error();for(const u of state.units)scene.remove(u.group);for(const b of state.buildings.filter(b=>b.userBuilt))removeBuilding(b);state.buildings=state.buildings.filter(b=>!b.userBuilt);state.units=[];pickables.length=0;for(const b of state.buildings)register(b.group,b);state.nodes.forEach((n,i)=>{n.remaining=s.nodes[i]??n.remaining;n.group.visible=n.remaining>0;register(n.group,n);});for(const b of s.buildings){const built=makeBuilding(b.type,b.x,b.z,b.progress>=1,b.rotation||0);built.userBuilt=true;built.corner=!!b.corner;setProgress(built,b.progress);}for(const u of s.units)addUnit(u.x,u.z,u.name);Object.assign(state,{resources:s.resources,time:s.time,gathered:s.gathered,builtHome:s.builtHome,invited:s.invited});cancelPlacement();select(null);renderBuild();updateHUD();togglePause(false);toast('Tu barrio está de vuelta. Los vecinos esperan tus órdenes.');}catch{$('save-note').textContent='La partida guardada no se pudo leer.';}};
const mini=$('minimap'),mc=mini.getContext('2d');
const MINI_HALF=MAP_HALF+5;function miniScale(){const w=mini.width,h=mini.height,k=Math.min(w,h)/(MINI_HALF*2);return {w,h,k,ox:w/2,oy:h/2};}
function drawMinimap(){const {w,h,k,ox,oy}=miniScale(),mx=x=>ox+x*k,mz=z=>oy+z*k;mc.fillStyle='#6f7a62';mc.fillRect(0,0,w,h);mc.fillStyle='#8b9b70';mc.fillRect(mx(-MINI_HALF),mz(-MINI_HALF),MINI_HALF*2*k,MINI_HALF*2*k);mc.fillStyle='#777a70';mc.fillRect(mx(-MAP_HALF+1),mz(-MAP_HALF+1),(MAP_HALF-1)*2*k,(MAP_HALF-1)*2*k);for(const bx of BLOCKS)for(const bz of BLOCKS){mc.fillStyle='#b2b1a0';mc.fillRect(mx(bx-14),mz(bz-14),28*k,28*k);mc.fillStyle='#8b9b70';mc.fillRect(mx(bx-BLOCK_HALF),mz(bz-BLOCK_HALF),BLOCK_HALF*2*k,BLOCK_HALF*2*k);}mc.strokeStyle='#c1bba2';mc.lineWidth=1;mc.beginPath();mc.moveTo(mx(MAP_HALF+3),mz(-MINI_HALF));mc.lineTo(mx(MAP_HALF+3),mz(MINI_HALF));mc.stroke();for(const b of state.buildings){mc.fillStyle=b===state.selected?'#fff1b5':b.progress<1?'#c9b58c':'#dac7a1';mc.fillRect(mx(b.x-b.width/2),mz(b.z-b.depth/2),b.width*k,b.depth*k);}for(const n of state.nodes){mc.fillStyle=n.type==='wood'?'#b58157':n.type==='food'?'#668348':'#a8b67b';if(n.remaining>0)mc.fillRect(mx(n.x)-2,mz(n.z)-2,4,4);}mc.fillStyle='#f0d27d';for(const u of state.units){mc.beginPath();mc.arc(mx(u.x),mz(u.z),1.8,0,7);mc.fill();}const vw=(camera.right-camera.left)/camera.zoom*.75*k,vh=(camera.top-camera.bottom)/camera.zoom*.9*k;mc.strokeStyle='#f6edce99';mc.strokeRect(mx(controls.target.x)-vw/2,mz(controls.target.z)-vh/2,vw,vh);}
function lookAt(x,z){const turn=Math.atan2(camera.position.x-controls.target.x,camera.position.z-controls.target.z)-Math.atan2(CAMERA_OFFSET.x,CAMERA_OFFSET.z);controls.target.set(Math.max(-MAP_HALF,Math.min(MAP_HALF,x)),0,Math.max(-MAP_HALF,Math.min(MAP_HALF,z)));camera.position.copy(controls.target).add(CAMERA_OFFSET.clone().applyAxisAngle(new THREE.Vector3(0,1,0),turn));}
mini.onclick=e=>{const r=mini.getBoundingClientRect(),{w,h,k,ox,oy}=miniScale();lookAt(((e.clientX-r.left)/r.width*w-ox)/k,((e.clientY-r.top)/r.height*h-oy)/k);};
function updateHUD(){for(const r of ['wood','food','yerba']){$(r).textContent=Math.floor(state.resources[r]);const n=state.units.filter(u=>u.job===r).length;$(r+'-rate').textContent=n?`+${n}`:'+0';} $('pop').textContent=state.units.length;$('capacity').textContent=capacity();$('neighbor-count').textContent=state.units.length;$('clock').textContent=`${Math.floor(state.time/60).toString().padStart(2,'0')}:${Math.floor(state.time%60).toString().padStart(2,'0')}`;$('gathered').textContent=`${Math.min(30,Math.floor(state.gathered))}/30`;const goals=[state.gathered>=30,state.builtHome,state.invited];['goal-wood','goal-home','goal-neighbor'].forEach((id,i)=>$(id).classList.toggle('done',goals[i]));$('goal-count').textContent=`${goals.filter(Boolean).length}/3`;if(state.selected?.kind==='unit'&&$('unit-status'))$('unit-status').textContent=unitStatus(state.selected);if(state.selected?.kind==='resource'&&$('resource-left'))$('resource-left').textContent=Math.ceil(state.selected.remaining);if(state.selected?.kind==='building'&&state.selected.progress<1&&$('building-status'))$('building-status').textContent=`${Math.floor(state.selected.progress*100)}% construido`;document.querySelectorAll('[data-building]').forEach(btn=>btn.classList.toggle('unaffordable',!canAfford(state.resources,BUILDINGS[btn.dataset.building])));}
let lastTime=0,hudTime=0,productionTime=0,won=false;
function tick(dt){state.time+=dt;const boost=state.buildings.some(b=>b.type==='taller'&&b.progress>=1)?1.25:1;
 for(const u of state.units){if(u.path.length){const p=u.path[0],dx=p.x-u.x,dz=p.z-u.z,d=Math.hypot(dx,dz),step=dt*2.6;if(d<step){u.x=p.x;u.z=p.z;u.path.shift();}else{u.x+=dx/d*step;u.z+=dz/d*step;}u.group.rotation.y=Math.atan2(dx,dz);u.walk+=dt*12;u.legs[0].rotation.x=Math.sin(u.walk)*.6;u.legs[1].rotation.x=-Math.sin(u.walk)*.6;u.group.position.set(u.x,Math.abs(Math.sin(u.walk))*.035,u.z);continue;}
 u.legs.forEach(l=>l.rotation.x=0);if(!u.job||!u.target)continue;
 if(u.job==='build'){const b=u.target;setProgress(b,Math.min(1,b.progress+dt/BUILDINGS[b.type].time));u.group.rotation.y=Math.atan2(b.x-u.x,b.z-u.z);u.group.position.y=Math.sin(state.time*9)*.035;if(b.progress>=1){u.job=null;u.target=null;u.group.position.y=0;if(b.type==='casa_chorizo')state.builtHome=true;toast(`${b.name} terminado. El barrio sigue creciendo.`);renderSelection();}}
 else {const node=u.target;if(node.remaining<=0){u.job=null;u.target=null;toast(`${u.name} terminó: ese recurso se agotó.`);continue;}u.work+=dt;u.group.rotation.y=Math.atan2(node.x-u.x,node.z-u.z);u.group.rotation.z=Math.sin(state.time*4)*.045;if(u.work>=1.25){u.work-=1.25;const amount=Math.min(node.remaining,2*(node.type==='wood'?boost:1));node.remaining-=amount;state.resources[node.type]+=amount;if(node.type==='wood')state.gathered+=amount;if(node.remaining<=0){node.remaining=0;node.group.visible=false;u.job=null;u.target=null;u.group.rotation.z=0;}}}
 }
 productionTime+=dt;if(productionTime>=5){productionTime-=5;for(const b of state.buildings.filter(b=>b.progress>=1)){if(b.type==='huerta')state.resources.food+=3;if(b.type==='almacen')state.resources.yerba+=b.corner?2:1;}}
 if(state.gathered>=30&&state.builtHome&&state.invited&&!won){won=true;toast('¡Echaste raíces! Seguí construyendo: este barrio tiene mucho por contar.');}

}
function animate(time){requestAnimationFrame(animate);const dt=Math.min((time-lastTime)/1000,.05);lastTime=time;animateWorld(state.paused?0:dt,time/1000);if(!state.paused){tick(dt);let dx=0,dz=0;if(keys.has('w')||keys.has('arrowup'))dz-=1;if(keys.has('s')||keys.has('arrowdown'))dz+=1;if(keys.has('a')||keys.has('arrowleft'))dx-=1;if(keys.has('d')||keys.has('arrowright'))dx+=1;if(dx||dz){const forward=new THREE.Vector3().subVectors(controls.target,camera.position);forward.y=0;forward.normalize();const right=new THREE.Vector3(-forward.z,0,forward.x);const move=right.multiplyScalar(dx).add(forward.multiplyScalar(-dz)).multiplyScalar(dt*15/camera.zoom);const next=controls.target.clone().add(move);if(Math.abs(next.x)<MAP_HALF&&Math.abs(next.z)<MAP_HALF){controls.target.add(move);camera.position.add(move);}}}if(state.selected){selectionRing.position.set(state.selected.x,.3,state.selected.z);}destinationTTL-=dt;if(destinationTTL<0)destinationRing.visible=false;controls.update();hudTime+=dt;if(hudTime>.25){hudTime=0;updateHUD();drawMinimap();}renderer.render(scene,camera);}
function resize(){const aspect=innerWidth/innerHeight;camera.left=-23*aspect;camera.right=23*aspect;camera.top=23;camera.bottom=-23;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
addEventListener('resize',resize);resize();renderSelection();renderBuild();updateHUD();drawMinimap();refreshIcons();requestAnimationFrame(animate);
setTimeout(()=>toast('Bienvenido a Tero Cosechado. Materiales, soja y un mate: empecemos el barrio.'),900);
// A small read-only snapshot supports reproducible browser QA without coupling tests to rendering.
window.gameSnapshot=()=>({resources:{...state.resources},units:state.units.map(u=>({name:u.name,x:u.x,z:u.z,job:u.job,path:u.path.length})),buildings:state.buildings.map(b=>({type:b.type,x:b.x,z:b.z,rotation:b.rotation,progress:b.progress})),capacity:capacity(),paused:state.paused,time:state.time,selected:state.selected?.name,placing:state.placing,gathered:state.gathered});
if(import.meta.env.DEV)window.gameInspect={
  project(x,z,y=0){const p=new THREE.Vector3(x,y,z).project(camera);return{x:(p.x+1)/2*innerWidth,y:(1-p.y)/2*innerHeight};},
  resources(){return state.nodes.map(n=>({type:n.type,x:n.x,z:n.z,remaining:n.remaining}));},
  plots(type){return allPlacements(BUILDINGS[type]).filter(p=>canPlace(p,type)).map(({x,z,side,slot,block,corner})=>({x,z,side,slot,block,corner}));},
  look(x,z){lookAt(x,z);},
  renderStats(){const t=performance.now();renderer.render(scene,camera);return {ms:+(performance.now()-t).toFixed(2),...renderer.info.render,geometries:renderer.info.memory.geometries};},
  route(sx,sz,x,z){return findPath(sx,sz,x,z);},
  stage(progress){const b=state.buildings.find(b=>b.progress<1);if(b)setProgress(b,progress);return b&&{x:b.x,z:b.z};}
};

// Optional browser-agent integration reuses the visible game's own actions.
const modelContext=document.modelContext;
if(modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tools=[
  {name:'read_town_state',title:'Consultar Tero Cosechado',description:'Lee recursos, vecinos, edificios y estado de la partida actual.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length)throw Error('Se esperaba un objeto vacío.');return window.gameSnapshot();}},
  {name:'start_building_placement',title:'Preparar una construcción',description:'Abre la vista previa de un edificio. No lo construye ni gasta recursos: el jugador elige el lote y confirma.',inputSchema:{type:'object',properties:{type:{type:'string',enum:Object.keys(BUILDINGS)}},required:['type'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.type!=='string'||!Object.hasOwn(BUILDINGS,input.type)||Object.keys(input).length!==1)throw Error('Tipo de construcción inválido.');if(state.paused)throw Error('La partida está pausada.');if(!canAfford(state.resources,BUILDINGS[input.type]))throw Error('Recursos insuficientes.');if(!state.units.some(u=>!u.job&&!u.path.length))throw Error('No hay un vecino disponible.');beginPlacement(input.type);return{placing:state.placing,requiresPlayerConfirmation:true};}}
 ];
 for(const tool of tools){try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

